### PR TITLE
GH-22: Fork JVM for every test in sink module

### PR DESCRIPTION
**Pull request by artembilan**
Fixes spring-cloud-stream-app-starters/gemfire#22

### CODE REVIEW

**Comment by artembilan** [comment]
For more info: https://maven.apache.org/surefire/maven-surefire-plugin/examples/fork-options-and-parallel-execution.html

Especially this one:

> `forkCount=1`/`reuseForks=false` executes each test class in its own JVM process, one after another.

**Comment by tzolov** [comment]
LGTM.  
This is plausible solution and i guess the only way to verify it is to test it on Jenckins?

**Review by tzolov — APPROVED** [review]
This might work. Lest test it on Jenkins

**Comment by tzolov** [comment]
rebased and merged at ffa153b2c81f8e803ef4e759244591bf655d026f

**Pull request closed without merging**
